title: Shogi Hellas

feed:
  path: mypath
author:
  name: Hikarikwai
description: >-
  Πληροφορίες σχετικά με το 1ο Πανελλήνιο Τουρνουά Σόγκι
baseurl: "/shogi-hellas"

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: classic

header_pages:
  - rules.md
  - schedule.md
  - venue.md