title: Shogi Hellas

feed:
  path: mypath
author:
  name: Stefanos Mandalas
  email: >-
    stefanosmandalas@gmail.com
    hikarikwaiclub@outlook.com
description: >-
  Information about the 1st Greek Shogi ISF Qualifiers
baseurl: "/shogi-hellas"

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: classic

header_pages:
  - rules.md
  - schedule.md
  - venue.md